osc=no
title-bar=no
osd-bar=no
autocreate-playlist=same
hr-seek=yes
save-position-on-quit
keepaspect-window=no
snap-window=yes
geometry=1280x720
keep-open=yes
ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]